import json, sys
INP=sys.argv[1] if len(sys.argv)>1 else "index.html"
OUT=sys.argv[2] if len(sys.argv)>2 else "index.html"
lines=open(INP,encoding='utf-8').read().split('\n')
mi=next(i for i,l in enumerate(lines) if l.startswith('const MAPDATA = '))
me=next(i for i,l in enumerate(lines) if l.startswith('const META = '))
MAP=json.loads(lines[mi][len('const MAPDATA = '):].rstrip().rstrip(';'))
META=json.loads(lines[me][len('const META = '):].rstrip().rstrip(';'))
GOV={'MDG':'Semi-presidential republic','NER':'Transitional / provisional','MLI':'Transitional / provisional','BFA':'Transitional / provisional','TCD':'Presidential republic','SOM':'Parliamentary republic','GTM':'Presidential republic','GIN':'Transitional / provisional','BEN':'Presidential republic','BDI':'Presidential republic','SSD':'Presidential republic','HTI':'Transitional / provisional','DOM':'Presidential republic','HND':'Presidential republic','TGO':'Presidential republic','SLE':'Presidential republic','NIC':'Presidential republic','SLV':'Presidential republic','COG':'Presidential republic','LBR':'Presidential republic','CAF':'Presidential republic','PSE':'Semi-presidential republic','MRT':'Presidential republic','CRI':'Presidential republic','PAN':'Presidential republic','ERI':'One-party state','BIH':'Parliamentary republic','JAM':'Parliamentary monarchy','GMB':'Presidential republic','GAB':'Transitional / provisional','MDA':'Parliamentary republic','ALB':'Parliamentary republic','LSO':'Parliamentary monarchy','GNB':'Semi-presidential republic','SVN':'Parliamentary republic','GNQ':'Presidential republic','MKD':'Parliamentary republic','XKX':'Parliamentary republic','TLS':'Semi-presidential republic','TTO':'Parliamentary republic','MUS':'Parliamentary republic','DJI':'Presidential republic','COM':'Presidential republic','GUY':'Presidential republic','SLB':'Parliamentary monarchy','SUR':'Parliamentary republic','MNE':'Parliamentary republic','MLT':'Parliamentary republic','MDV':'Presidential republic','CPV':'Semi-presidential republic','BLZ':'Parliamentary monarchy','BHS':'Parliamentary monarchy','VUT':'Parliamentary republic','BRB':'Parliamentary republic'}
REG={'ETH':'Authoritarian','AGO':'Authoritarian','MOZ':'Authoritarian','MDG':'Hybrid regime','CIV':'Hybrid regime','NER':'Authoritarian','MLI':'Authoritarian','BFA':'Authoritarian','TCD':'Authoritarian','SOM':'Authoritarian','SEN':'Flawed democracy','GTM':'Hybrid regime','GIN':'Authoritarian','BEN':'Authoritarian','BDI':'Authoritarian','SSD':'Authoritarian','HTI':'Authoritarian','DOM':'Flawed democracy','PNG':'Flawed democracy','TGO':'Authoritarian','SLE':'Hybrid regime','HKG':'Hybrid regime','KGZ':'Authoritarian','NIC':'Authoritarian','SRB':'Hybrid regime','SLV':'Hybrid regime','COG':'Authoritarian','LBR':'Hybrid regime','CAF':'Authoritarian','PSE':'Authoritarian','MRT':'Authoritarian','PAN':'Flawed democracy','ERI':'Authoritarian','BIH':'Hybrid regime','JAM':'Flawed democracy','GMB':'Hybrid regime','GAB':'Authoritarian','MDA':'Flawed democracy','ALB':'Hybrid regime','LSO':'Hybrid regime','GNB':'Authoritarian','SVN':'Flawed democracy','GNQ':'Authoritarian','MKD':'Flawed democracy','XKX':'Hybrid regime','TLS':'Flawed democracy','TTO':'Flawed democracy','CYP':'Flawed democracy','MUS':'Full democracy','DJI':'Authoritarian','FJI':'Flawed democracy','COM':'Authoritarian','GUY':'Flawed democracy','SLB':'Flawed democracy','BTN':'Hybrid regime','LUX':'Full democracy','SUR':'Flawed democracy','MNE':'Flawed democracy','MLT':'Flawed democracy','MDV':'Hybrid regime','CPV':'Flawed democracy','BRN':'Authoritarian','BLZ':'Flawed democracy','BHS':'Flawed democracy','VUT':'Flawed democracy','BRB':'Flawed democracy','CRI':'Full democracy'}
def lm(key):
    L=next(l for l in META['layers'] if l['key']==key); return {d['label']:d['color'] for d in L['legend']}
GCOL=lm('govtype'); RCOL=lm('regime'); ng=nr=0
for f in MAP['features']:
    p=f['properties']; iso=p.get('iso3')
    if iso in GOV and not p.get('govtype'): p['govtype']=GOV[iso]; p['color_govtype']=GCOL[GOV[iso]]; ng+=1
    if iso in REG and not p.get('regime'): p['regime']=REG[iso]; p['color_regime']=RCOL[REG[iso]]; nr+=1
lines[mi]='const MAPDATA = '+json.dumps(MAP,separators=(',',':'))+';'
open(OUT,'w',encoding='utf-8').write('\n'.join(lines))
print(f"OK: govtype +{ng}, regime +{nr}")
